name: crescent
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_html: ^3.0.0-alpha.6
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  intl: ^0.17.0
  riverpod_annotation: ^1.0.6
  auto_route: ^5.0.3
  cohost_api:
    path: 'cohost_dart/'
  cached_network_image: ^3.2.2
  flutter_markdown: ^0.6.13
  webview_flutter: ^3.0.4
  markdown: ^6.0.1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  flutter_svg: ^1.1.6
  flutter_secure_storage: ^6.0.0
  photo_view: ^0.14.0
  flutter_inappwebview: ^5.7.2
  freezed_annotation: ^2.2.0
  html: ^0.15.1
  http: ^0.13.5
  path_provider: ^2.0.11
  metadata_fetch:
    git:
      url: https://github.com/MagTuxGit/metadata_fetch.git
  flutter_avif: ^1.0.0
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  riverpod_generator: ^1.0.4
  auto_route_generator: ^5.0.3
  isar_generator: ^3.0.5
  build_runner: any
  freezed: ^2.2.1
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon/icon.png"


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  generate: true

  fonts:
  - family: AtkinsonHyperlegible
    fonts:
      - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf
      - asset: assets/fonts/AtkinsonHyperlegible-Bold.ttf
        weight: 700
      - asset: assets/fonts/AtkinsonHyperlegible-Italic.ttf
        style: italic
  assets:
    - assets/
    - assets/images/
    - assets/web/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
